import adze from './log';
export * from './configuration';
import Formatter from './formatters/formatter';
import {
  setup,
  teardown,
  isBrowser,
  addPadding,
  applyStyles,
  formatAssert,
  formatCount,
  formatIf,
  formatLabel,
  formatNamespace,
  initialCaps,
} from './functions';
export * from './middleware';
export * from './formatters/common';
export * from './formatters/standard';
export * from './formatters/json';
import {
  AdzeConstructor,
  CommonLogConfiguration,
  Configuration as IConfiguration,
  ConfigurationData,
  ConsoleStyle,
  DefaultTerminatorMethod,
  FilterConfig,
  Filters,
  Format,
  FormatterConstructor,
  HrTime,
  HttpMethod,
  HttpStatus,
  HttpVersion,
  IObject,
  Label,
  LabelMap,
  Level,
  LevelConfiguration,
  LevelSelector,
  LogData,
  LogListener,
  Method,
  MethodWithArgs,
  MethodWithoutArgs,
  Modifier,
  ModifierData,
  ModifierName,
  NormalizedLevelSelector,
  SpecialMethod,
  SpecialMethodWithLeader,
  TableData,
  Terminator,
  TimestampFormatter,
  UserConfiguration,
  console_styles,
} from './_types';
export {
  AdzeConstructor,
  CommonLogConfiguration,
  IConfiguration,
  ConfigurationData,
  ConsoleStyle,
  DefaultTerminatorMethod,
  FilterConfig,
  Filters,
  Format,
  Formatter,
  FormatterConstructor,
  HrTime,
  HttpMethod,
  HttpStatus,
  HttpVersion,
  IObject,
  Label,
  LabelMap,
  Level,
  LevelConfiguration,
  LevelSelector,
  LogData,
  LogListener,
  Method,
  MethodWithArgs,
  MethodWithoutArgs,
  Modifier,
  ModifierData,
  ModifierName,
  NormalizedLevelSelector,
  SpecialMethod,
  SpecialMethodWithLeader,
  TableData,
  Terminator,
  TimestampFormatter,
  UserConfiguration,
  addPadding,
  applyStyles,
  console_styles,
  formatAssert,
  formatCount,
  formatIf,
  formatLabel,
  formatNamespace,
  initialCaps,
  isBrowser,
  setup,
  teardown,
};
export * from './constants';
export default adze;
