import adze from './log';
export * from './configuration';
import Formatter from './formatters/formatter';
import {
  setup,
  teardown,
  isBrowser,
  addPadding,
  applyStyles,
  formatAssert,
  formatCount,
  formatIf,
  formatLabel,
  formatNamespace,
  initialCaps,
} from './functions';
export * from './middleware';
export * from './formatters/common';
export * from './formatters/standard';
export * from './formatters/json';
import {
  type AdzeConstructor,
  type CommonLogConfiguration,
  type Configuration as IConfiguration,
  type ConfigurationData,
  type ConsoleStyle,
  type DefaultTerminatorMethod,
  type FilterConfig,
  type Filters,
  type Format,
  type FormatterConstructor,
  type HrTime,
  type HttpMethod,
  type HttpStatus,
  type HttpVersion,
  type IObject,
  type Label,
  type LabelMap,
  type Level,
  type LevelConfiguration,
  type LevelSelector,
  type LogData,
  type LogListener,
  type Method,
  type MethodWithArgs,
  type MethodWithoutArgs,
  type Modifier,
  type ModifierData,
  type ModifierName,
  type NormalizedLevelSelector,
  type SpecialMethod,
  type SpecialMethodWithLeader,
  type TableData,
  type Terminator,
  type TimestampFormatter,
  type UserConfiguration,
  console_styles,
} from './_types';
export {
  type AdzeConstructor,
  type CommonLogConfiguration,
  type IConfiguration,
  type ConfigurationData,
  type ConsoleStyle,
  type DefaultTerminatorMethod,
  type FilterConfig,
  type Filters,
  type Format,
  Formatter,
  type FormatterConstructor,
  type HrTime,
  type HttpMethod,
  type HttpStatus,
  type HttpVersion,
  type IObject,
  type Label,
  type LabelMap,
  type Level,
  type LevelConfiguration,
  type LevelSelector,
  type LogData,
  type LogListener,
  type Method,
  type MethodWithArgs,
  type MethodWithoutArgs,
  type Modifier,
  type ModifierData,
  type ModifierName,
  type NormalizedLevelSelector,
  type SpecialMethod,
  type SpecialMethodWithLeader,
  type TableData,
  type Terminator,
  type TimestampFormatter,
  type UserConfiguration,
  addPadding,
  applyStyles,
  console_styles,
  formatAssert,
  formatCount,
  formatIf,
  formatLabel,
  formatNamespace,
  initialCaps,
  isBrowser,
  setup,
  teardown,
};
export * from './constants';
export default adze;
